##### DBMS Type #####
[source_db]
dbms = "oracle"
#dbms = "mysql"
#dbms = "postgresql"
#dbms = "sql_server"
#dbms = "tibero"

[target_db]
dbms = "oracle"
#dbms = "mysql"
#dbms = "postgresql"
#dbms = "sql_server"
#dbms = "tibero"


##### DBMS Connection string #####
[source_connection_string]
DSN = "OracleODBC"           #For Oracle
DBQ = "localhost:1521/source_db" #For Oracle

DRIVER='{Driver Name}'       #For other DB
SERVER='localhost'           #For other DB
DATABASE='mydatabase'        #For other DB

[target_connection_string]
DSN = "OracleODBC"           #For Oracle
DBQ = "localhost:1521/target_db" #For Oracle

DRIVER='{Driver Name}'       #For other DB
SERVER='localhost'           #For other DB
DATABASE='mydatabase'        #For other DB

# Connection string Example 
# MySQL, PostgreSQL, SQL Server
#'DRIVER={Driver Name};SERVER=localhost;DATABASE=mydatabase;UID=username;PWD=password;'

# ORACLE
#"DSN=OracleODBC;DBQ=source_db;UID=uwername;PWD=password;"

# Tibero
#"DSN=OracleODBC;UID=uwername;PWD=password;"



##### Schema & User#####
[scott]
uid = 'scott'
pwd = 'tiger'

[your_db]
uid = 'your_uid'
pwd = 'your_pwd'
